apiVersion: maistra.io/v1
kind: ServiceMeshMember
metadata:
  name: default
  namespace: {{ .Values.appsNamespace }}
spec:
  controlPlaneRef:
    name: basic-install
    namespace: {{ .Values.smNamespace }}
